chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(
        regex=r'^$',
        view=views.MessageListView.as_view(),
        name='list'
    ),
    # url(
    #     regex=r'^(?P<username>[\w.@+-]+)/$',
    #     view=views.ProfileDetailView.as_view(),
    #     name='detail'
    # ),

]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
import notifications.urls

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('pairup.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^inbox/notifications/', include(
        notifications.urls, namespace='notifications')),
    url(r'^profile/', include('user_profile.urls', namespace='profile')),
    url(r'^message/', include('chat.urls', namespace='message')),
    url(r'^', include('landing.urls', namespace='landing')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

landing/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(
        regex=r'^$',
        view=views.HomeListView.as_view(template_name='landing/home.html'),
        name='home'
    ),
    url(
        regex=r'^ajax/landing_location/$',
        view=views.HomeLocationAjaxView.as_view(),
        name='home_location'
    ),
    # url(
    #     regex=r'^s*',
    #     view=views.NotificationsView.as_view(),
    # ),
    # url(
    #     '^inbox/notifications/',
    #     include(notifications.urls, namespace='notifications')
    # ),
]

notifications/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views


app_name = 'notifications'
urlpatterns = [
    url(r'^$', views.AllNotificationsList.as_view(), name='all'),
    url(r'^notifications_ajax$', views.NotificationsAjaxView.as_view(), name='notifications_ajax'),
    url(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    url(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    url(r'^mark-as-read/(?P<slug>\d+)/$', views.mark_as_read, name='mark_as_read'),
    url(r'^mark-as-unread/(?P<slug>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    url(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    url(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    url(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
]

pairup/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    # url(
    #     regex=r'^(?P<username>[\w.@+-]+)/$',
    #     view=views.UserDetailView.as_view(),
    #     name='detail'
    # ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

user_profile/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^public_toggle$',
        view=views.PublicToggleFormView.as_view(),
        name='public_toggle'
    ),
    url(
        regex=r'^check_public$',
        view=views.CheckPublicAjaxView.as_view(),
        name='check_public'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.ProfileDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/edit_preference/$',
        view=views.PreferenceUpdateView.as_view(),
        name='edit_preference'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/edit_profile/$',
        view=views.ProfileUpdateView.as_view(),
        name='edit_profile'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/pair_request/$',
        view=views.PairRequestView.as_view(),
        name='pair_request'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/pair_response/$',
        view=views.PairResponseView.as_view(),
        name='pair_response'
    ),
]

pairup/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

pairup/users/forms.py
# from allauth.socialaccount.forms import SignupForm
# from allauth.account.forms import SetPasswordField, PasswordField
# from allauth.account import app_settings
# from allauth.account.utils import user_field, user_email, user_username
from django.utils.translation import ugettext_lazy as _
from django import forms
# from django.forms import forms
# from allauth.account.forms import BaseSignupForm
from user_profile.models import Profile


# Don't opt for password setting with social login. Defeats the point of social login.
# https://stackoverflow.com/questions/47121638/how-to-set-password-in-user-table-when-user-is-signup-using-google-or-facebook-d
# class SocialPasswordedSignupForm(BaseSignupForm):

#     password1 = SetPasswordField(label=_("Password"))
#     password2 = SetPasswordField(label=_("Confirm Password"))

#     def __init__(self, *args, **kwargs):
#         self.sociallogin = kwargs.pop('sociallogin')
#         user = self.sociallogin.user
#         # TODO: Should become more generic, not listing
#         # a few fixed properties.
#         initial = {'email': user_email(user) or '',
#                    'username': user_username(user) or '',
#                    'first_name': user_field(user, 'first_name') or '',
#                    'last_name': user_field(user, 'last_name') or ''}
#         kwargs.update({
#             'initial': initial,
#             'email_required': kwargs.get('email_required',
#                                          app_settings.EMAIL_REQUIRED)})
#         super(SocialPasswordedSignupForm, self).__init__(*args, **kwargs)

#     def save(self, request):
#         adapter = get_adapter()
#         user = adapter.save_user(request, self.sociallogin, form=self)
#         self.custom_signup(request, user)
#         return user

#     def clean(self):
#         super(SocialPasswordedSignupForm, self).clean()
#         if "password1" in self.cleaned_data \
#                 and "password2" in self.cleaned_data:
#             if self.cleaned_data["password1"] \
#                     != self.cleaned_data["password2"]:
#                 raise forms.ValidationError(_("You must type the same password"
#                                               " each time."))

#     def raise_duplicate_email_error(self):
#         raise forms.ValidationError(
#             _("An account already exists with this e-mail address."
#               " Please sign in to that account first, then connect"
#               " your %s account.")
#             % self.sociallogin.account.get_provider().name)

#     def custom_signup(self, request, user):
#         password = self.cleaned_data['password1']
#         user.set_password(password)
#         user.save()


# class SocialPasswordedSignupForm(SignupForm):

#     password1 = SetPasswordField(max_length=128,label=("Password"))
#     password2 = PasswordField(max_length=128, label=("Password (again)"))

# #taken from https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py

#     def clean_password2(self):
#         if ("password1" in self.cleaned_data and "password2" in self.cleaned_data):
#             if (self.cleaned_data["password1"] != self.cleaned_data["password2"]):
#                 raise forms.ValidationError(("Your passwords do not match"))
#         return self.cleaned_data["password2"]

#     def signup(self, request, user):
#         user.set_password(self.user, self.cleaned_data["password1"])
#         user.save()


class SignupForm(forms.Form):

    learn1 = forms.CharField(max_length=50, label='Learn', required=False)
    teach1 = forms.CharField(max_length=50, label='Teach', required=False)

    class Meta:
        model = Profile

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.pop("autofocus", None)
        self.fields['email'].widget.attrs.update({"autofocus": "autofocus"})

    def clean(self):
        cleaned_data = super().clean()
        if not self.cleaned_data['learn1'] or self.cleaned_data['teach1']:
            raise forms.ValidationError("Specify at least one skill to offer or something you'd like to learn")
        else:
            return cleaned_data

    def save(self, user):
        # if not self.cleaned_data['learn1'] or self.cleaned_data['teach1']:
        #     raise forms.ValidationError("Specify at least one")
        user.is_profile_to.learn1 = self.cleaned_data['learn1']
        user.is_profile_to.teach1 = self.cleaned_data['teach1']
        user.save()
        user.is_profile_to.save()

pairup/users/views.py
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import ListView, RedirectView, UpdateView
from django.shortcuts import render_to_response
from django.template import RequestContext

from allauth.account.forms import AddEmailForm, ChangePasswordForm
# from allauth.account.views import SignupView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import User
# from .forms import initialPreferenceForm

# class MySignupView(SignupView):
#     initial_preference_form = initialPreferenceForm

#     def get_context_data(self, *args, **kwargs):
#         # Pass the extra form to this view's context
#         context = super(
#             MySignupView, self).get_context_data(*args, **kwargs)
#         context['initial_preference_form'] = initialPreferenceForm
#         return context

#     def form_valid(self, form):
#         self.user = form.save(self.request)
#         return super(MySignupView, self).form_valid(form)
# class MyEmailPasswordView(LoginRequiredMixin, EmailView):
#     template_name = 'account/joint_email_pass.html'
#     form_class = AddEmailForm
#     change_password_form = ChangePasswordForm
#     success_url = reverse_lazy('change_email_pass')

#     def __init__(self, *args, **kwargs):
#         super(MyEmailPasswordView, self).__init__(**kwargs)

#     def get_success_url(self):
#         return reverse('change_email_pass')

#     def get_context_data(self, *args, **kwargs):
#         # Pass the extra form to this view's context
#         context = super(
#             MyEmailPasswordView, self).get_context_data(*args, **kwargs)
#         context['change_password_form'] = ChangePasswordForm
#         # V2! -- need to change success url?
#         # redirect back to joint form view instead of single form view
#         # Try subclassing AllAuth's views and changin the success urls?
#         # print(self.get_success_url())
#         # print(super(MyEmailPasswordView, self).get_success_url())
#         return context


# class UserDetailView(LoginRequiredMixin, DetailView):
#     model = User
#     # These next two lines tell the view to index lookups by username
#     slug_field = 'username'
#     slug_url_kwarg = 'username'

# for custom 404.
# def handler404(request):
#     response = render_to_response('404.html', {},
#                                   context_instance=RequestContext(request))
#     response.status_code = 404
#     return response


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        # return reverse('users:detail',
                       # kwargs={'username': self.request.user.username})
        return reverse('users:update')


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['is_active']
    template_name = 'account/joint_email_pass.html'
    add_email_form = AddEmailForm
    change_password_form = ChangePasswordForm
    success_url = reverse_lazy('change_email_pass')

    # def __init__(self, *args, **kwargs):
    #     super(MyEmailPasswordView, self).__init__(**kwargs)

    def get_context_data(self, *args, **kwargs):
        # Pass the extra form to this view's context
        context = super(
            UserUpdateView, self).get_context_data(*args, **kwargs)
        context['change_password_form'] = ChangePasswordForm
        context['add_email_form'] = AddEmailForm
        # V2! -- need to change success url?
        # redirect back to joint form view instead of single form view
        # Try subclassing AllAuth's views and changin the success urls?
        # print(self.get_success_url())
        # print(super(MyEmailPasswordView, self).get_success_url())
        return context
    # we already imported User in the view code above, remember?
    # model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:update')

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)

pairup/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

pairup/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% load notifications_tags %}

<html lang="en" class="fontawesome-i2svg-pending">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Pairap{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway" rel="stylesheet">


    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    {# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous"> #}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />


    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    {# <link href="{% static 'css/project.css' %}" rel="stylesheet"> #}
    {# <link href="{% static 'css/chat.css' %}" rel="stylesheet"> #}

    {% endblock %}

  </head>

  <body>
    {% include "nav.html" %}
    <div class="container pt-5 mt-5 mb-5">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
      {% endblock content %}


    </div> <!-- /container -->

    {% if not request.path == '/message/' %}
      <hr class="col-md-2" />
        <div class="container-fluid mt-5 mb-2">
          <div class="row footer">
          {% include "footer.html" %}
          </div>
        </div>
    {% endif %}
    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    {% include "js.html" %}

    {% block javascript %}
    {% endblock javascript %}
  </body>
</html>

pairup/templates/footer.html
{% load i18n %}

<div class="col-xs-6 mx-auto">
    <ul class="list-inline">
        <li class="list-inline-item"><a href="#">ABOUT</a></li>
        <li class="list-inline-item"><a href="#">CONTACT</a></li>
        <li class="list-inline-item"><a href="#">TERMS</a></li>
        <li class="list-inline-item"><a href="#">PRIVACY</a></li>
        <li class="list-inline-item"><a href="#">BLOG</a></li>
    </ul>
</div>

pairup/templates/js.html
{% load static i18n %}
{% load notifications_tags %}

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Required by Bootstrap v4 beta -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<!-- Your stuff: Third-party javascript libraries go here -->
{# TODO: move to head #}
{# <script src="{% static 'js/packs/fa-regular.js' %}"></script> #}
<script src="{% static 'js/fontawesome-all.js' %}"></script>
<script src="{% static 'js/reconnecting-websocket.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/fileinput.min.js"></script>

{# <script src="//cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script> #}
{# TODO: DL, no CDNs #}

{# Use custom notify script #}
{# {% include "notifications/box.html" %} #}
<script src="{% static 'notifications/notify.js' %}"></script>

{% register_notify_callbacks callbacks='fill_notification_list, fill_notification_badge' fetch=10 refresh_period=5 %}

{# Make sure CSRF comes before files dependent on AJAX calls #}
{# CSRF #}
<script type="text/javascript">
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
</script>
<!-- place project specific Javascript in this file -->
<script src="{% static 'js/project.js' %}"></script>
{# chat socket related #}
<script src="{% static 'js/main.js' %}"></script>

pairup/templates/nav.html
{% load i18n %}
{% load notifications_tags %}

<div class="">
  <nav class="navbar fixed-top navbar-expand-md navbar-light bg-light">
    <a class="navbar-brand ml-3" href="{% url 'landing:home' %}">Pairap</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto mr-5 align-items-center">

        {% if request.user.is_authenticated %}
          {% if request.user.is_profile_to.profile_photo_thumbnail %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'profile:detail' username=request.user.username %}">
            <img class="profile_photo_thumbnail" src="{{ request.user.is_profile_to.profile_photo_thumbnail.url }}" />
            {{ request.user }}
          </a>
          </li>
          {% else %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'profile:detail' username=request.user.username %}">
            <i class="far fa-user"></i>
          </a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'message:list' %}">
            <i class="far fa-envelope"></i>
            </a>
          </li>
          <li class="nav-item dropdown" data-open-notifications="{% url 'notifications:notifications_ajax' %}">
            <a href="#" class="dropdown-toggle nav-link" id="dropdownMenuLink" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
               <i class="far fa-inbox"></i>
               {# {% live_notify_badge badge_class="badge badge-warning" %} #}
                <span class="caret"></span>
              {% live_notify_list list_class="dropdown-menu dropdown-menu-right dropdown-menu-scroll live_notify_list" %}
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:update' %}">
            <i class="far fa-cog"></i>
          {# {% trans "Preferences" %} #}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">{% trans "logout" %}</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
          </li>
          <li class="nav-item">
            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

</div>