chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(
        regex=r'^$',
        view=views.MessageListView.as_view(),
        name='list'
    ),
    # url(
    #     regex=r'^(?P<username>[\w.@+-]+)/$',
    #     view=views.ProfileDetailView.as_view(),
    #     name='detail'
    # ),

]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
import notifications.urls

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('pairup.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^inbox/notifications/', include(
        notifications.urls, namespace='notifications')),
    url(r'^profile/', include('user_profile.urls', namespace='profile')),
    url(r'^message/', include('chat.urls', namespace='message')),
    url(r'^', include('landing.urls', namespace='landing')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

user_profile/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^public_toggle$',
        view=views.PublicToggleFormView.as_view(),
        name='public_toggle'
    ),
    url(
        regex=r'^check_public$',
        view=views.CheckPublicAjaxView.as_view(),
        name='check_public'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.ProfileDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/edit_preference/$',
        view=views.PreferenceUpdateView.as_view(),
        name='edit_preference'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/edit_profile/$',
        view=views.ProfileUpdateView.as_view(),
        name='edit_profile'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/pair_request/$',
        view=views.PairRequestView.as_view(),
        name='pair_request'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/pair_response/$',
        view=views.PairResponseView.as_view(),
        name='pair_response'
    ),
]

user_profile/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import (
    Http404,
    get_object_or_404,
    redirect,
    reverse,
)
from django.views.generic import (
    DetailView,
    UpdateView,
    FormView,
    TemplateView,
    View
)
from .models import Profile
from chat.models import Chat
from chat.models import Pair
from .forms import (
    PreferenceUpdateForm,
    ProfileUpdateForm,
    CredentialImageFormSet,
    PairRequestForm,
    PublicToggleForm,
)
from .mixins import AjaxFormMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from user_profile.permissions import has_perm_or_is_owner


# Create your views here.


# class ProfilePublicAjaxView(View):
#     def post(self, request, *args, **kwargs):
#         print("ONE")
#         if self.request.is_ajax():
#             public = self.request.GET.get('t_or_f')

#             if self.request.user.is_authenticated:
#                 user = self.request.user
#                 # Profile.objects.filter(user=user).update(last_location=Point((lat, lon)))
#                 p = Profile.objects.get(user=user)
#                 setattr(p, 'last_location', Point(lon, lat, srid=4326))
#                 p.save()

#             return JsonResponse({'key': "value"}, safe=False)


class PublicToggleFormView(AjaxFormMixin, FormView):
    form_class = PublicToggleForm
    success_url = '/form-success/'
    template_name = 'user_profile/profile_detail.html'

    def get_form_kwargs(self):
        kwargs = super(PublicToggleFormView, self).get_form_kwargs()
        profile = Profile.objects.get(user=self.request.user)
        kwargs.update({'instance': profile})
        return kwargs


class CheckPublicAjaxView(View):

    def post(self, request):
        if self.request.is_ajax():
            # TODO: error message
            # PERMISSION-TO-CLICK-LINK CHECKS HERE
            if self.request.user.is_authenticated():
                if self.request.user.is_profile_to.public:
                    data = {
                        'message': "Allow button click?"
                    }
                    # custom permission checks
                    return JsonResponse(data)
                else:
                    data = {
                        'error': "ERRO HERE",
                        'message': "EORR MESG"
                    }
                    return JsonResponse(data, status=400)
            else:
                data = {
                    'message': "Log in to get started!"
                }
                return JsonResponse(data, status=400)


class ProfileDetailView(DetailView):
    template_name = 'user_profile/profile_detail.html'

    def is_pair(self, **kwargs):
        # Method for the template to check whether the request.user &
        # current profile object have a pair relationship.
        # Does not determine which user is R & A
        current_profile = self.get_object()
        requesting_profile = Profile.objects.get(
            user__username=self.request.user)
        if Pair.objects.filter(requester=requesting_profile,
                               accepter=current_profile).exists():
            return True
        elif Pair.objects.filter(requester=current_profile,
                                 accepter=requesting_profile).exists():
            return True
        return False

    def pending_to_requester(self, **kwargs):
        # Method for the template to determine which CTA button to display.
        # Differentiates profiles btwn R & A
        current_profile = self.get_object()
        requester = Profile.objects.get(
            user__username=self.request.user)
        if requester.is_requester.filter(
                accepter=current_profile,
                requester=requester,
                pending=True).exists():
            return True
        return False

    def pending_to_accepter(self, **kwargs):
        current_profile = self.get_object()
        accepter = Profile.objects.get(
            user__username=self.request.user)
        if accepter.is_accepter.filter(
                accepter=accepter,
                requester=current_profile,
                pending=True).exists():
            return True
        return False

    def accepted_pair(self, **kwargs):
        pass

    def get_object(self, *args, **kwargs):
        username = self.kwargs.get('username')
        if username is None:
            raise Http404
        obj = get_object_or_404(Profile, user__username__iexact=username)
        return obj

    def get_context_data(self, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            visitor = Profile.objects.get(
                user=self.request.user)
            current_profile = self.get_object()
            context['public_toggle_form'] = PublicToggleForm(
                instance=current_profile
            )
            context['is_pair'] = visitor.is_pair(
                current_profile)
            context['visitor_has_request_pending'] = visitor.has_request_pending(
                current_profile)
            context['visitor_has_response_pending'] = visitor.has_response_pending(
                current_profile)
            context['is_denied_pair'] = visitor.is_denied_pair(
                current_profile)
            context['is_accepted_pair'] = visitor.is_accepted_pair(
                current_profile)
        return context


class PreferenceUpdateView(LoginRequiredMixin, UpdateView):
    # permission_required = ('user_profile.change_profile')
    form_class = PreferenceUpdateForm
    model = Profile
    template_name = 'user_profile/preference_edit.html'
    raise_exception = True

    # def test_func(self):

    def get_object(self, *args, **kwargs):
        user_profile = self.kwargs.get('username')
        obj = get_object_or_404(Profile, user__username=user_profile)
        can_edit = has_perm_or_is_owner(
            self.request.user,
            'user_profile.change_profile',
            instance=obj,
        )
        if not can_edit:
            raise Http404
        return obj

    def form_valid(self, form):
        # instance = form.save(commit=False)
        # if no edits, dont save
        # form.instance.user = self.request.user
        # print(form.instance)
        return super(PreferenceUpdateView, self).form_valid(form)


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    form_class = ProfileUpdateForm
    template_name = 'user_profile/profile_edit.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        data = super(ProfileUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['credential_image'] = CredentialImageFormSet(
                self.request.POST, self.request.FILES, instance=self.object)
        else:
            data['credential_image'] = CredentialImageFormSet(
                instance=self.object)
        return data

    def get_object(self, *args, **kwargs):
        user_profile = self.kwargs.get('username')
        obj = get_object_or_404(Profile, user__username=user_profile)
        can_edit = has_perm_or_is_owner(
            self.request.user,
            'user_profile.change_profile',
            instance=obj,
        )
        if not can_edit:
            raise Http404
        return obj

    def form_valid(self, form):
        data = self.get_context_data()
        formset = data['credential_image']
        if formset.is_valid():
            print("1", formset)
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.object.get_absolute_url())
        else:
            print("WTF")

        instance = form.save(commit=False)
        instance.user = self.request.user
        return super(ProfileUpdateView, self).form_valid(form)


class PairRequestView(LoginRequiredMixin, UserPassesTestMixin, FormView):
    form_class = PairRequestForm
    template_name = 'user_profile/pair_request.html'
    raise_exception = True

    def test_func(self):
        # Test that viewers of this page have public as True. The recipients must also be True
        # cannot request with yourself.
        # Cannot request with someone who has denied you
        responding_profile = Profile.objects.get(
            user__username=self.request.user)
        requesting_profile = Profile.objects.get(
            user__username=self.kwargs['username'])
        if not responding_profile == requesting_profile:
            if responding_profile.public is True and requesting_profile.public is True:
                return True
        return False

    def get_success_url(self, **kwargs):
        return reverse('profile:detail', args=[self.kwargs['username']])

    def get_context_data(self, **kwargs):
        # Get username from kwargs to add context to the pair request page
        context = super(PairRequestView, self).get_context_data(**kwargs)
        context['request_to_user'] = self.kwargs.get('username')
        return context

    def get_form_kwargs(self, *args, **kwargs):
        requester_obj = Profile.objects.get(
            user__username=self.request.user)
        accepter_obj = Profile.objects.get(
            user__username=self.kwargs.get('username'))

        what_will_you_teach_set = requester_obj.get_teach()
        what_will_you_learn_set = accepter_obj.get_teach()

        kwargs = super().get_form_kwargs()

        # Pass additional kwargs to the form
        kwargs['learn_from_partner'] = what_will_you_learn_set
        kwargs['teach_to_partner'] = what_will_you_teach_set

        return kwargs

    def form_valid(self, form):
        super(PairRequestView, self).form_valid(form)

user_profile/templates/user_profile/pair_request.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row col-sm-6 col-sm-offset-3">
<h1>Make a new Pair Request to {{ request_to_user }}</h1>

<form enctype="multipart/form-data" method="POST" action="{% url 'profile:pair_request' username=view.kwargs.username %}">
    {% csrf_token %}
    {% include 'includes/bs4_pair_request_form.html' with form=form %}

    {# {{form|crispy}} #}
    <input class='btn btn-primary' type="submit" name='request' value="Send a request!" />

</form>

</div>
{% endblock content %}

user_profile/templates/user_profile/pair_response.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row col-sm-6 col-sm-offset-3">
<h1>{{ respond_to_user }} would like to pair with you!</h1>


<form enctype="multipart/form-data" method="POST" action="{% url 'profile:pair_response' username=view.kwargs.username %}">
    {% csrf_token %}
    {{form|crispy}}
    {# TODO: If none to teach, ... #}
    {{ respond_to_user }} would like to learn {{requester_learns}} from you. <br />
    {{ respond_to_user }} can teach {{requester_teaches}} <br />
    <input class='btn btn-primary' type="submit" name='accept' value="Accept" />
    <input class='btn btn-warning' type="submit" name='deny' value="Deny" />

</form>

</div>
{% endblock content %}

user_profile/templates/user_profile/preference_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-6 mr-auto ml-auto">
        <h1>Update your preferences</h1>
        <form enctype="multipart/form-data" method="POST" action="{% url 'profile:edit_preference' username=request.user %}"> {% csrf_token %}
            {% include 'includes/bs4_preference_update_form.html' with form=form %}
            <input class="btn-primary" type="submit" value="submit" />
        </form>
    </div>
</div>
{% endblock content %}

user_profile/templates/user_profile/profile_detail.html
{% extends 'base.html' %}
{% load static %}
{% block head_title %} {{ object.user }} | {{ block.super }} {% endblock head_title %}
{% block content %}
<div class="row mb-5">
    <div class="col-md-8">
    {% if request.user == object.user %}
        <a href="{% url 'profile:edit_preference' username=object.user %}">Edit your preferences</a>
    {% endif %}

    <!-- Learn/teach set intro -->
    <h1>
        <p>Hey! 👋 </p>
        <p>I've got the skills to teach
        {% for item in object.get_teach %}
            <em>{{ item|default_if_none:"" }}</em>{% if not forloop.last%}, {% endif %}
        {% endfor %}
        </p>
        <p>
        I'm looking to learn
        {% for item in object.get_learn %}
            <em>{{ item|default_if_none:"" }}</em>{% if not forloop.last%}, {% endif %}
        {% endfor %}
        </p>
    </h1>
    </div>

    <div class="col-md-3">
        <h3>{{ object|upper }}</h3>
        <div class="mb-3">
            {% if object.profile_photo %}
            <picture>
              <source media="(min-width: 650px)" srcset="{{ object.profile_photo.url }}">
              <source media="(min-width: 465px)" srcset="{{ object.profile_photo.url }}">
              <img src="{{ object.profile_photo.url }}" alt="profile photo" style="width:200px;">
            </picture>
            {% else %}
            <picture>
              <source media="(min-width: 650px)" srcset="{% static 'images/profile_photo_default/alien.png'%}">
              <source media="(min-width: 465px)" srcset="{% static 'images/profile_photo_default/alien.png'%}">
              <img src="{% static 'images/profile_photo_default/alien.png'%}" alt="default profile photo" style="width:200px;">
            </picture>
            {% endif %}
        </div>

        <div class="form-public-toggle">
        {% if request.user == object.user %}
        <strong>Public</strong>
        <form class="ajax-public-toggle-form" method="POST" action='{% url "profile:detail" username=object.user %}' data-url='{% url "profile:public_toggle" %}'>
            {# <label class="switch">
              <input type="checkbox">
              <span class="slider"></span>
            </label> #}
            {% include 'includes/bs4_public_toggle_form.html' with form=public_toggle_form %}
        </form>
        <div id="public_toggle_form_errors" class="form-error" style="display: none;"></div>
        {% endif %}
        </div>
    </div>
</div>

<div class="row mb-5">
    <div class="col-md-12">
    {% if request.user == object.user %}
        <a href="{% url 'profile:edit_profile' username=object.user %}">Edit your profile</a>
    {% endif %}

    <!-- Credentials introduction -->
    <h3>About {{ object }}</h3>
    <p>{{object.introduction}}</p>
    </div>
</div>
    <!-- Credential images -->

<div class="row mb-5">
    {% comment %}

    <div class="col-8 mx-auto">
    {% for img in object.credentialimage.all %}
        <span>
            <img src="{{MEDIA_URL}}{{img.image}}" class="img-responsive" width="100" />
            <!-- {{img.image}}{{img.description}} -->
        </span>
    {% endfor %}
    </div>
    {% endcomment %}

<div class="mx-auto">


<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">

        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body p-0">
        {# carousel #}
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            {% for img in object.credentialimage.all %}
            {% if forloop.counter == 0 %}
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            {% else %}
            <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}"></li>
            {% endif %}
            {% endfor %}

          </ol>
          <div class="carousel-inner">
            {% for img in object.credentialimage.all %}
            {% if forloop.counter == 1 %}
                <div class="carousel-item active">
                    <img class="w-100" src="{{MEDIA_URL}}{{img.image}}" alt="User's uploaded image" />
                </div>
            {% else %}
            <div class="carousel-item">
              <img class="d-block w-100" src="{{MEDIA_URL}}{{img.image}}" alt="User's uploaded image" />
            </div>
            {% endif %}
            {% endfor %}
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>


    {% for img in object.credentialimage.all %}
    <button type="button" class="p-0" data-toggle="modal" data-target="#exampleModalCenter">
        <span>
            <img src="{{MEDIA_URL}}{{img.image}}" class="d-block img-fluid" width="150" />
            <!-- {{img.image}}{{img.description}} -->
        </span>
    </button>
    {% endfor %}


{# col #}
</div>




</div>


<!-- Skills shared -->
<div class="row">

    <div class="col-md-3">
        <h3>Skills Shared</h3>
        <p>
            <strong>surfing </strong> with <strong>/p/surfmeister35 </strong>
        </p>
    </div>




    <!-- References -->

    <div class="col-md-6">
        <h3>References</h3>
        {%comment%}{% for reference in object.reference %} {%endcomment%}
        <p><strong>/p/surfmeister35</strong> says: <br />
            <em>"He rocks! Helped me get the hang of AngularJS within a day. Definitely meet up with him if you want to get started with x,y,z"</em>
        </p>
        {%comment%}
        {% endfor %}
        {%endcomment%}
    </div>


    <!-- Changelog -->
    <div class="col-md-3">
        <h3>Changelog</h3>
        {% for cl in object.changelog.all reversed %}
        <p>[ Date: {{cl.log_date}} ]</p>
        <p>[ Preferences: {{cl.log_preference}} ]</p>
        <hr />
        {% endfor %}
    </div>
</div>


<div class="row">

    <div class="col-xs-2 mr-auto ml-auto">
    {% if is_pair %}
        {% if visitor_has_request_pending %}
            <button class="btn btn-primary btn-no-hover">
                Request to {{object.user | upper}} is Pending
            </button>
        {% elif visitor_has_response_pending %}
            <a class='btn btn-primary' href="{% url 'profile:pair_response' object.user %}">Respond to {{object.user | upper}}!</a>
        {% elif is_accepted_pair %}
        {# delete, write review for, block #}
        we are a pair!
        {% elif is_denied_pair %}
            <a class='btn btn-primary pairing-CTA-btn' href="{% url 'profile:pair_request' object.user %}" data-check-public-url='{% url "profile:check_public" %}'>
                Send {{object.user | upper}} a Pair Request
            </a>
            <div id="public_check_errors" class="form-error" style="display: none;">
            </div>
        {% endif %}
    {% elif request.user != object.user %}
        <a class='btn btn-primary pairing-CTA-btn' href="{% url 'profile:pair_request' object.user %}" data-check-public-url='{% url "profile:check_public" %}'>
            Send {{object.user | upper}} a Pair Request
        </a>
        <div id="public_check_errors" class="form-error" style="display: none;">
        </div>
    {% endif %}

    </div>
</div>


{% endblock content %}

user_profile/templates/user_profile/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-6 mr-auto ml-auto">
        <h1>Update your profile</h1>
        {% if form.errors.non_field_errors %}
            {{form.errors}}
        {% endif %}
        <form enctype="multipart/form-data" method="POST" action="{% url 'profile:edit_profile' username=request.user %}"> {% csrf_token %}
            {# {{ form|crispy }} #}
            {% include 'includes/bs4_profile_update_form.html' with form=form %}
<hr>
            {{ credential_image.management_form }}
            {% for form in credential_image %}
                {% include 'includes/bs4_credential_image_form.html' with form=form %}
                {# {{ form }} #}
            {% endfor %}

            <input class="btn-primary" type="submit" value="submit" />
        </form>
    </div>
</div>
{% endblock content %}

{% block javascript %}
<script>
// $(document).ready(function(){
//     var url1 = 'http://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/FullMoon2010.jpg/631px-FullMoon2010.jpg',
//         url2 = 'http://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Earth_Eastern_Hemisphere.jpg/600px-Earth_Eastern_Hemisphere.jpg';
//     // initialize with defaults
//     $("input[type='file']").fileinput({
//         initialPreview: [url1, url2],
//         initialPreviewAsData: true,
//         initialPreviewConfig: [
//             {caption: "Moon.jpg", downloadUrl: url1, size: 930321, width: "120px", key: 1},
//             {caption: "Earth.jpg", downloadUrl: url2, size: 1218822, width: "120px", key: 2}
//         ],
//         deleteUrl: "/site/file-delete",
//         overwriteInitial: false,
//         maxFileSize: 100,
//         initialCaption: "The Moon and the Earth"
//     });


//     // with plugin options
//     $("input[type='file']").fileinput({'showUpload':false, 'previewFileType':'any'});
// })
</script>
{% endblock javascript %}