chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(
        regex=r'^$',
        view=views.MessageListView.as_view(),
        name='list'
    ),
    # url(
    #     regex=r'^(?P<username>[\w.@+-]+)/$',
    #     view=views.ProfileDetailView.as_view(),
    #     name='detail'
    # ),

]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
import notifications.urls

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('pairup.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^inbox/notifications/', include(
        notifications.urls, namespace='notifications')),
    url(r'^profile/', include('user_profile.urls', namespace='profile')),
    url(r'^message/', include('chat.urls', namespace='message')),
    url(r'^', include('landing.urls', namespace='landing')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

landing/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(
        regex=r'^$',
        view=views.HomeListView.as_view(template_name='landing/home.html'),
        name='home'
    ),
    url(
        regex=r'^ajax/landing_location/$',
        view=views.HomeLocationAjaxView.as_view(),
        name='home_location'
    ),
    # url(
    #     regex=r'^s*',
    #     view=views.NotificationsView.as_view(),
    # ),
    # url(
    #     '^inbox/notifications/',
    #     include(notifications.urls, namespace='notifications')
    # ),
]

landing/models.py
from django.db import models

# Create your models here.

landing/views.py
from django.views.generic import ListView, View
from django.http import JsonResponse
from django.db.models import Q
from functools import reduce
import operator
from django.contrib.gis.geos import Point

from django.contrib.gis.measure import D
from django.contrib.gis.db.models.functions import Distance

from user_profile.models import Profile
# Create your views here.
# from django.views.decorators.csrf import csrf_exempt

# @csrf_exempt


# class NotificationsView(View):
#     def get(self, request, *args, **kwargs):
#         profile = Profile.objects.get(user__username=self.request.user)
#         notifs = profile.user.notifications.unread()
#         # print(notifs)
#         return render(request, 'base.html', {'notifs': notifs})


class HomeLocationAjaxView(View):
    def get(self, request, *args, **kwargs):
        if self.request.is_ajax():
            lat = self.request.GET.get('lat')
            # lat = self.request.GET.get('lat', 'provide Seoul default?')
            lon = self.request.GET.get('lon')
            lat = float(lat)
            lon = float(lon)

            round(lat, 4)
            round(lon, 4)

            if self.request.user.is_authenticated:
                user = self.request.user
                # Profile.objects.filter(user=user).update(last_location=Point((lat, lon)))
                p = Profile.objects.get(user=user)
                setattr(p, 'last_location', Point(lon, lat, srid=4326))
                p.save()

            return JsonResponse({'key': "value"}, safe=False)


class HomeListView(ListView):
    model = Profile
    context_object_name = 'all_user_posts'
    paginate_by = 6

    queryset = Profile.objects.filter(public=True).order_by('-created')
    # TODO CLEAN UP and combine views -- see: PSEUDO on trello
    # def get_queryset(self):
    #     # return Profile.objects.filter(public=True).order_by('-created')
    #     return Profile.objects.filter(public=True)

    # def get_context_data(self, *args, **kwargs):
    #     query = self.request.GET.get('q')
    #     qs = Profile.objects.all()
    #     if query:
    #         qs = qs.filter(introduction__icontains=query)

    def get_queryset(self):
        result = super(HomeListView, self).get_queryset()

        # Search functions
        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(learn1__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(learn2__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(introduction__icontains=q) for q in query_list))
            )
        else:
            # At least one pref filled out, location HAS been shared once.
            # TODO: incorporate those who havent shared location with a general location
            if self.request.user.is_authenticated:
                current_user = Profile.objects.get(user=self.request.user)
                if current_user.last_location:
                    user_list = Profile.objects.annotate(
                        distance_away=Distance(
                            'last_location', current_user.last_location
                        )).filter(
                        Q(learn1__isnull=False) | Q(learn2__isnull=False) |
                        Q(learn3__isnull=False) | Q(teach1__isnull=False) |
                        Q(teach2__isnull=False) | Q(teach3__isnull=False),
                        public=True,
                        last_location__distance_lte=(
                            current_user.last_location, D(km=500)))
                    # TODO Order closest to farthest
                    # paginate
                    result = user_list
        return result

landing/templates/landing/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h3>Learn something new</h3>
        <p>
            {# TODO clean up/ If not registered, CTA #}
        {% comment %}
        {{request.user}}
        {{user}}
        {{sql_queries}}
        {{messages}}
        {{DEFAULT_MESSAGE_LEVELS}}
        {% endcomment %}
        </p>
        {% comment %}
            accounts is not a registered namespace
        {% if not request.user.is_authenticated %}
            <a href="{% url 'accounts:register' %}"><input class="btn btn-default" type="submit" value="Get Started &raquo;"><input type="hidden" name=""></a>
        {% endif %}
        {% endcomment %}
    </div>
</div>

<!-- Search -->
<!-- TEMPORARY -->
<div class="row">
    <div class="col-md-10 mr-5 ml-5">
        <form class='form' method="GET" action=".">
            <div class="input-group">
                <input class="form-control form-control-lg" id="search-input" type="text" name="q" placeholder="" value="{{request.GET.q}}" />
                <span class="input-group-btn">
                <button class="btn btn-lg btn-success" id="search-button" type="submit" /><i class="fas fa-search"></i></button>
                </span>
            </div>
        </form>
    </div>
</div>
{% comment %}
{# <div class="row">
    <div class="col-md-12">
    <div class="sort_search">
        <h5>Sort by:</h5>
        <ul>
            <li>-Teach</li>
            <li>+Learn</li>
            <li>Tech</li>
            <li>Language</li>
            <li>...</li>
        </ul>
    </div>
    </div>
</div>
 #}
{% endcomment %}

<form id="location" role="form" data-submit-location-ajax="{% url 'landing:home_location' %}" method="post">{% csrf_token %}
        <div class="form-group">
            <input id="id_latitude" name="latitude" type="hidden" class="form-control"></input>
        </div>
        <div class="form-group">
            <input id="id_longitude" name="longitude" type="hidden" class="form-control"></input>
        </div>
</form>


<!-- Postings/results ListView -->
{% include 'landing/post_list.html' %}

{% endblock content %}


{% block javascript %}
    <script src="{% static 'js/typed/typed.min.js' %}"></script>
    <script language="javascript" type="text/javascript">
        // typed effect
        var strings = ['BUS120', 'BUS140 @ SNU', 'speaking French', '5-string bass', 'graphic design', 'swimming - backstroke', 'water-coloring', '' ]
        function shuffleStrings(array) {
            let counter = array.length;
            // While there are elements in the array
            while (counter > 0) {
                // Pick a random index
                let index = Math.floor(Math.random() * counter);
                // Decrease counter by 1
                counter--;
                // And swap the last element with it
                let temp = array[counter];
                array[counter] = array[index];
                array[index] = temp;
            }
            return array;
        }
        shuffled = shuffleStrings(strings)
        var typed = new Typed("#search-input", {
            strings: shuffled,
            attr: 'placeholder',
            typeSpeed: 30,
            backSpeed: 20,
            loop: true,
            cursorChar: '|',
            showCursor: true,
            // fadeOut: true,
            // fadeOutClass: 'typed-fade-out',
            // autoInsertCss: true,
        });
        document.querySelector('#search-input').
            addEventListener('click', function() {
                typed.reset(restart=false);
            });


        // location grab
        navigator.geolocation.getCurrentPosition(function (position) {
            var lat = document.getElementById('id_latitude');
            var lon = document.getElementById('id_longitude');
            lat.value = position.coords.latitude;
            lon.value = position.coords.longitude;

            $.ajax({
                headers: { "X-CSRFToken": '{{csrf_token}}' },
                method: 'get',
                dataType: 'json',
                cache: false,
                url: $('#location').attr('data-submit-location-ajax'),
                data: {'lat': lat.value, 'lon': lon.value}
            }).done(function(data) {
                 // data is filled with Django result, here {'key': value}
                /* TODO: remember the call has been made and it's registered on Django side */
            }).fail(function(data) {
                alert('fatal error!');
            }).always(function() {
                /* whatever the result, always do something here */
            });
        });
    </script>

{% endblock javascript %}

landing/templates/landing/post_list.html
{% load humanize %}
{% load humanize_distance %}

<div class="row mt-5 mb-2">
    <div class="col-md-3 mr-auto ml-auto">
    {% if is_paginated %}
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}
    </div>
</div>

<div class="row">
    <div class="card-columns">

        {% for post in all_user_posts %}
        <div class="card m-2" id="post-item">
            <div class="card-body">
                <a id="post-link" href='{{ post.get_absolute_url }}'>

                    <div class="list-lead-box">
                    {% if post.get_learn %}
                        <span class="card-text list-to-learn-lead">
                            <small class="text-muted">wants to learn:</small>
                        </span>
                        {% for item in post.get_learn %}
                            <strong>
                            {{item|default_if_none:""}}
                            </strong>
                            {% if not forloop.last %}
                                ,
                            {% endif %}
                        {% endfor %}
                    {% else %}
                    <em class="card-text text-muted list-muted-text">not looking for anything at the moment!</em>
                    {% endif %}
                    </div>

                    <div class="list-lead-box">
                    {% if post.get_teach %}
                        <span class="card-text list-to-teach-lead">
                            <small class="text-muted">able to teach:</small>
                        </span>

                        {% for item in post.get_teach %}
                        <strong>
                            {{item|default_if_none:"nothing here.."}}
                        </strong>
                        {% if not forloop.last %}
                            ,
                        {% endif %}
                        {% endfor %}
                    {% else %}
                        <em class="card-text text-muted list-muted-text">nothing to share at the moment!</em>
                    {% endif %}
                    </div>

                    <div class="mt-2 list-more-info">
                        <span class="card-text list-listing-by">by
                            <a href='{{ post.get_absolute_url }}'>{{ post.user }}</a>
                        </span>
                        {% if request.user.is_authenticated %}
                        {# instead, if location is approved.. #}
                        - <span class="card-text">{{ post.distance_away|distance_format }} away</span>
                        {% endif %}
                        {# -<span class="list-listing-date"> {{ post.created|naturaltime }}</span> #}
                        <!-- {{ post.created|date:'DATETIME_FORMAT' }} -->
                    </div>
                </a>
            </div>
        </div>

        {% endfor %}
    </div>
</div>

<div class="row mt-2">
    <div class="col-md-3 mr-auto ml-auto">
    {% if is_paginated %}
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}
    </div>
</div>